In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
from sklearn import metrics
from sklearn.metrics import confusion_matrix 
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
import statsmodels.formula.api as smf


In [ ]:

fault = pd.read_csv(r'/content/drive/My Drive/fault.csv')

In [ ]:
print (fault)


                Va           Vb           Vc  ...           Ib           Ic  Type
0      133338.3100  133338.7913  133338.8461  ...  2638.823999  2638.834568     1
1      133340.0105  133338.9365  133339.1682  ...  2638.773319  2638.788228     1
2      133337.1638  133338.7130  133337.9788  ...  2638.800935  2638.880679     1
3      133340.7818  133338.8560  133340.2906  ...  2638.789176  2638.747235     1
4      133337.0056  133338.9416  133336.8525  ...  2638.784389  2638.878001     1
5      133340.1968  133338.5196  133341.1581  ...  2638.803148  2638.741644     1
6      133338.2996  133339.3229  133336.4465  ...  2638.781191  2638.840543     1
7      133338.3390  133338.1648  133340.9669  ...  2638.810563  2638.758322     1
8      133340.4481  133339.5829  133337.2515  ...  2638.789984  2638.798487     1
9      133336.2037  133338.0520  133339.6192  ...  2638.812028  2638.776380     1
10     133342.2403  133339.5197  133338.9653  ...  2638.803078  2638.778566     1
11     133335.00

In [ ]:
abc = np.split(fault, [6], axis=1)
x = abc[0]
abc1 = np.split(fault, [6], axis=1)
y = abc1[1]
print (x)
print (y)

                Va           Vb  ...           Ib           Ic
0      133338.3100  133338.7913  ...  2638.823999  2638.834568
1      133340.0105  133338.9365  ...  2638.773319  2638.788228
2      133337.1638  133338.7130  ...  2638.800935  2638.880679
3      133340.7818  133338.8560  ...  2638.789176  2638.747235
4      133337.0056  133338.9416  ...  2638.784389  2638.878001
5      133340.1968  133338.5196  ...  2638.803148  2638.741644
6      133338.2996  133339.3229  ...  2638.781191  2638.840543
7      133338.3390  133338.1648  ...  2638.810563  2638.758322
8      133340.4481  133339.5829  ...  2638.789984  2638.798487
9      133336.2037  133338.0520  ...  2638.812028  2638.776380
10     133342.2403  133339.5197  ...  2638.803078  2638.778566
11     133335.0090  133338.2909  ...  2638.811342  2638.782229
12     133342.6536  133339.1325  ...  2638.811625  2638.789089
13     133335.4217  133338.7758  ...  2638.811856  2638.777052
14     133341.4744  133338.6136  ...  2638.810795  2638

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size = 0.75,
                                     test_size = 0.25,random_state = 438)
y_train=y_train.values.ravel()
print (x_train)
print (y_train)

                Va           Vb  ...           Ib           Ic
210    133281.8747  133277.7831  ...  2187.495560  2187.437125
6220   133266.7393  133347.2262  ...    36.394384    26.349258
2991   133376.8893  133149.2049  ...  1364.446349    58.514122
266    133286.5984  133273.1684  ...  2187.479974  2187.447072
8278   133342.7348  133637.2375  ...  2088.730900  2059.205258
5588   133051.7481  133346.3970  ...    40.368842  1514.257165
789    133292.8171  133238.7948  ...  1506.980792  1507.175270
7981   133407.7647  133304.7071  ...  1091.216961  1364.683117
1716   133271.8209  133243.1045  ...  1609.156474  1608.958535
7966   133362.0573  133302.4813  ...  1160.709309  1452.895557
4800   133115.0077  133348.4710  ...    48.670568  1240.586190
7191   133331.1987  133310.4850  ...  2239.807167  2445.192296
4717   133147.4181  133348.4676  ...    45.838005  1334.552685
4514   133180.8534  133352.0745  ...    40.050834  1579.493983
1424   133233.3047  133243.4464  ...  1857.598274  1857

#Linear Regression

In [ ]:
lin_reg_mod = LinearRegression()
lin_reg_mod.fit(x_train, y_train)
pred = lin_reg_mod.predict(x_test)
test_set_rmse = (np.sqrt(metrics.mean_squared_error(y_test, pred)))
print(test_set_rmse)


1.5050652782353364


# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier 

knn = KNeighborsClassifier(n_neighbors = 10).fit(x_train, y_train) 
  
# accuracy on X_test 
accuracy = knn.score(x_test, y_test) 
print (accuracy)
knn_predictions = knn.predict(x_test)  
cm = confusion_matrix(y_test, knn_predictions) 
print (cm)
a=cm.sum()
accuracy = (cm[0][0]+cm[1][1]+cm[2][2]+cm[3][3]+cm[4][4]+cm[5][5]+cm[6][6]+cm[7][7]+cm[8][8]+cm[9][9]+cm[10][10])/a
print("Accuracy: "+ str(accuracy*100)+"%")
# define one new instance
xnew = [[133338.31,133338.7913,133338.8461,2638.951258,2638.823999,2638.834568 ]]
# reading no 9321---BG fault--10
x1new =[[133340.056,133215.3098,133363.7837,37.2243164,2031.789353,43.84411799]]
# make a prediction
ynew = knn.predict(xnew) 
print("x=%s, Predicted=%s" % (xnew[0], ynew[0]))
y1new = knn.predict(x1new) 
print("x=%s, Predicted=%s" % (x1new[0], y1new[0]))

0.8808345120226309
[[147 107   0   0   0   0   0   0   0   0   0]
 [230  31   0   0   0   0   0   0   0   0   0]
 [  0   0 259   0   0   0   0   0   0   0   0]
 [  0   0   0 252   0   0   0   0   0   0   0]
 [  0   0   0   0 259   0   0   0   0   0   0]
 [  0   0   0   0   0 248   0   0   0   0   0]
 [  0   0   0   0   0   0 253   0   0   0   0]
 [  0   0   0   0   0   0   0 254   0   0   0]
 [  0   0   0   0   0   0   0   0 254   0   0]
 [  0   0   0   0   0   0   0   0   0 251   0]
 [  0   0   0   0   0   0   0   0   0   0 283]]
Accuracy: 88.08345120226309%
x=[133338.31, 133338.7913, 133338.8461, 2638.951258, 2638.823999, 2638.834568], Predicted=1.0
x=[133340.056, 133215.3098, 133363.7837, 37.2243164, 2031.789353, 43.84411799], Predicted=10.0


# Gaussian NB

In [ ]:
from sklearn.naive_bayes import GaussianNB 
from sklearn.metrics import confusion_matrix 
gnb = GaussianNB().fit(x_train, y_train) 
gnb_predictions = gnb.predict(x_test) 
  
# accuracy on X_test 
accuracy = gnb.score(x_test, y_test) 
print (accuracy)
cm = confusion_matrix(y_test, gnb_predictions) 
print (cm)
a=cm.sum()
accuracy = (cm[0][0]+cm[1][1]+cm[2][2]+cm[3][3]+cm[4][4]+cm[5][5]+cm[6][6]+cm[7][7]+cm[8][8]+cm[9][9]+cm[10][10])/a
print("Accuracy: "+ str(accuracy*100)+"%")

0.8125884016973126
[[ 70 184   0   0   0   0   0   0   0   0   0]
 [ 80 181   0   0   0   0   0   0   0   0   0]
 [  0   0 259   0   0   0   0   0   0   0   0]
 [  0   0   0 252   0   0   0   0   0   0   0]
 [  0   0   0   0 259   0   0   0   0   0   0]
 [  0   0   0   0   0 248   0   0   0   0   0]
 [  0   0   0   0   0   0 253   0   0   0   0]
 [  0   0   0   0   0   0   0 254   0   0   0]
 [  0   0   0   0   0   0   0   0 254   0   0]
 [  0   0   0   0   0   0   0   0   0 251   0]
 [  0   0   0   0   0   0  16 250   0   0  17]]
Accuracy: 81.25884016973126%


# Random Forest

In [ ]:
#from sklearn.preprocessing import StandardScaler
#https://stackabuse.com/random-forest-algorithm-with-python-and-scikit-learn/
#sc = StandardScaler()
#x_train = sc.fit_transform(x_train)
#x_test = sc.transform(x_test)
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)
# Calculate the absolute errors
#errors = abs(y_pred - y_test)
# Print out the mean absolute error (mae)
#print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')
#cm = confusion_matrix(y_test,y_pred) 
#print (cm)
#a=cm.sum()
#accuracy = (cm[0][0]+cm[1][1]+cm[2][2]+cm[3][3]+cm[4][4]+cm[5][5]+cm[6][6]+cm[7][7]+cm[8][8]+cm[9][9]+cm[10][10])/a
#print("Accuracy: "+ str(accuracy*100)+"%")
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.13396172206506365
Mean Squared Error: 0.10384302982309437
Root Mean Squared Error: 0.32224684610263354


# Support Vector

In [ ]:
from sklearn.svm import SVC
from sklearn.datasets import make_regression
clf = SVC(gamma='auto')
clf.fit(x_train, y_train)
y_pred=clf.predict(x_test)
cm = confusion_matrix(y_test,y_pred) 
print (cm)
a=cm.sum()
accuracy = (cm[0][0]+cm[1][1]+cm[2][2]+cm[3][3]+cm[4][4]+cm[5][5]+cm[6][6]+cm[7][7]+cm[8][8]+cm[9][9]+cm[10][10])/a
print("Accuracy: "+ str(accuracy*100)+"%")
# new instances where we do not know the answer   https://machinelearningmastery.com/make-predictions-scikit-learn/
XXnew, _ = make_regression(n_samples=40, n_features=6, noise=0.1,shuffle= False, random_state=438)
# make a prediction
yynew =clf.predict(XXnew)
# show the inputs and predicted outputs
for i in range(len(XXnew)):
	print("X=%s, Predicted=%s" % (XXnew[i], yynew[i]))
 

[[ 30 202   0   0   0   0   0   0   0   0  22]
 [201  38   0   0   0   0   0   0   0   0  22]
 [  0   0 121   0   0   0   0   0   0   0 138]
 [  0   0   0  99   0   0   0   0   0   0 153]
 [  0   0   0   0 143   0   0   0   0   0 116]
 [  0   0   0   0   0 116   0   0   0   0 132]
 [  0   0   0   0   0   0 124   0   0   0 129]
 [  0   0   0   0   0   0   0 136   0   0 118]
 [  0   0   0   0   0   0   0   0 127   0 127]
 [  0   0   0   0   0   0   0   0   0 113 138]
 [  0   0   0   0   0   0   0   0   0   0 283]]
Accuracy: 47.02970297029702%
X=[-0.39281113  0.44783922  1.76644421 -1.68342598  2.19980442 -0.90805776], Predicted=11.0
X=[-1.74846399 -0.11552773  0.6073476   0.40015329  1.45054919 -0.37870584], Predicted=11.0
X=[-0.54170837 -0.27975596 -0.07959293  0.32499052  0.47830461 -1.00810813], Predicted=11.0
X=[-0.69386095  0.48040675  1.87297643  0.37522705 -0.13767481  1.13622316], Predicted=11.0
X=[ 0.43706018  0.77071772  0.54289822  0.63626005 -2.17378495 -0.64845195], Predicte

# LR

In [ ]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)
predictions = logmodel.predict(x_test)
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))
print("Accuracy:",metrics.accuracy_score(y_test, predictions))
#
cm = confusion_matrix(y_test,predictions) 
print (cm)
a=cm.sum()
accuracy = (cm[0][0]+cm[1][1]+cm[2][2]+cm[3][3]+cm[4][4]+cm[5][5]+cm[6][6]+cm[7][7]+cm[8][8]+cm[9][9]+cm[10][10])/a
print("Accuracy: "+ str(accuracy*100)+"%")

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


              precision    recall  f1-score   support

         1.0       0.49      0.81      0.61       254
         2.0       0.53      0.20      0.29       261
         3.0       1.00      0.99      1.00       259
         4.0       0.99      1.00      1.00       252
         5.0       1.00      0.99      1.00       259
         6.0       0.99      1.00      1.00       248
         7.0       1.00      1.00      1.00       253
         8.0       1.00      1.00      1.00       254
         9.0       1.00      1.00      1.00       254
        10.0       1.00      1.00      1.00       251
        11.0       1.00      0.96      0.98       283

    accuracy                           0.90      2828
   macro avg       0.91      0.91      0.90      2828
weighted avg       0.91      0.90      0.90      2828

Accuracy: 0.9045261669024045
[[207  47   0   0   0   0   0   0   0   0   0]
 [208  53   0   0   0   0   0   0   0   0   0]
 [  0   0 257   2   0   0   0   0   0   0   0]
 [  0   0   0 252